name: Report

on:
  push:
    branches: [ main, develop ]

jobs:
  upload-artifact:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d-%m-%Y')"

      - name: Prepare environment
        run: |
          mkdir docs

      - name: Generate LSS report PDF
        uses: docker://pandoc/latex:2.18
        with:
          args: -d ./pandoc/latex.yml -o docs/LSSReport.pdf -M date:${{steps.date.outputs.date}}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          # name: reports-${{ steps.date.outputs.date }}
          name: lss-report
          path: docs
  download-artifact:
      needs: 
        - upload-artifact
      runs-on: ubuntu-18.04
      steps:
        - uses: actions/download-artifact@v3
          with:
            name: lss-report
            path: docs
        - name: Display structure of downloaded files
          run: ls -R
          working-directory: docs